name: basic workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Your name'
        required: true
        default: 'World'
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet
        run: |
          echo "hello ${{ github.event.inputs.name }}"
          echo "none"
      - name: Get runner IP
        run: curl https://api.ipify.org
